### ISSUE TITLE
Installing wallet-standard forces to install react

### ISSUE THREAD

**Issue by netanel-utila** [wallet-standard/wallet-standard#104]
└─┬ @solana/wallet-standard@1.1.2
  └─┬ @solana/wallet-standard-wallet-adapter@1.1.2
    └── @solana/wallet-standard-wallet-adapter-react@1.1.2

**Comment by steveluscher** [comment]
This is not the repository for `@solana/wallet-standard`. This is `@wallet-standard/wallet-standard`.
