### ISSUE TITLE
Decoupling Wallet UI from Dapp UI - perhaps by returning the API via `connect()`

### ISSUE THREAD

**Issue by stephenhuh** [wallet-standard/wallet-standard#3]
From the standard goals:
> Decouple the state of the wallet UI from the state of the dapp UI
Wallets should be presented as stateless, isolated, multi-tenant applications to dapps.
When a dapp acts upon a wallet, it should have no effect on any other dapp that may interact with the wallet.
Similarly, when a user interacts with the wallet UI, it should have no effect on any dapp.
When a user changes accounts or networks in the wallet UI, their intent is to see their assets or act with them in the context of the wallet UI.
After a dapp has connected to a wallet and discovered an account, the dapp should be able to request to sign using that account specifically.
When this occurs, the wallet should display account and network changes to sign and send transactions for the dapp, and then return to its previous context.

On these thoughts, is it possible for us to perhaps call a function such as `enable()` or maybe even `connect()` that returns an object with an API that is strictly read-only? e.g. pseudocode for a dapp

```
const api = await wallet.enable(); or wallet.enable(); // this method can throw or return false to handle cases of rejected connections.
// read only methods are returned
api.getChain();
api.getIcon();
api.getAccounts();

// only way to interact is via submission of tx
api.sendAndConfirm();

// (if needed) object can become invalidated if there's a need to reauthorize connection. 
```
Note this is a preliminary thought but I took some of the ideas from cardano's wallet's connections as well as some of eth's

**Comment by jordansexton** [comment]
This is largely implemented. Check out https://github.com/wallet-standard/wallet-standard/blob/master/packages/core/standard/src/wallet.ts --

The `accounts` field, and the `connect` method which returns `accounts`, contain `WalletAccount` objects. These are basically the API of the wallet when acting with an account. These accounts have features, which may be specific to the wallet's implementation and the chain.

And check out https://github.com/wallet-standard/wallet-standard/blob/master/packages/wallets/backpack/src/wallet.ts for how a wallet can wrap its existing API with the standard.

**Comment by jordansexton** [comment]
The API being per account means that an account with an empty `features` API is effectively a read-only account. The wallet can either expose these via `wallet.accounts` or an app could specifically request read-only access to accounts by calling `wallet.connect({ features: [] })`.

**Comment by jordansexton** [comment]
Closing as this is implemented.
