### ISSUE TITLE
Brave doesn't work if there is a partial sign with different fee payer

### ISSUE THREAD

**Issue by yamijuan** [wallet-standard/wallet-standard#83]
We have the case where we want to cover any transaction fees for the user so the way we currently have it is as follows:
* Ask the backend for a transaction
* Creates a transactions
* set `feePayer` as the keypair's public key we have stored
* partially sign the tx `transacation.partialSign(feePayerKP)
* serialize the tx in base64
* send to the frontend
* recover transaction with `Buffer.from` and `Transaction.from`
* call `sendTransaction` from wallet adapter

What happens at this point is brave wallet pops up but without any action, just the account info and it gets stuck there forever

What we did to fix it is instead of calling `sendTransaction` from wallet adapter, we call `signTransaction` and sign the tx and the send it with `connection.sendRawTransaction` after serialize it. This fix got us to believe there is an issue in brave implementation on `wallet.signAndSendTransaction` that's being used in brave's `sendTransaction` in its adapter

Also removing the feepayer and the signature works too. Someone from our team thinks it might be an issue with signature order in brave. 

with @steveluscher 's permission, here is a video https://drive.google.com/file/d/14jX-Fqds9oBCwDgNkcJxWmmodB_tpX-P/view

**Comment by steveluscher** [comment]
@yamijuan, can you quickly test what happens here if you call `window.solana.signAndSendTransaction()` directly?

**Comment by mcintyre94** [comment]
FWIW this is a use case we've seen with Solana Pay, where the transaction served will be partially signed either to pay fees or to send a token to the user

I've been able to repro this issue with a slightly modified version of our solana-pay-scaffold: https://github.com/mcintyre94/solana-pay-scaffold (change-fee-payer branch)

To test it, copy .env.example to .env, put any private key with devnet SOL in as `WALLET_PRIVATE_KEY`, yarn, yarn dev. Click connect wallet and then send with wallet on the transaction request page (localhost:3000/)

The `main` branch uses a simple transaction with no other signers and works correctly in Brave, the `change-fee-payer` branch has the same issue reported here

I've also tested the `window.solana.signAndSendTransaction()` and the behaviour is exactly the same

**Comment by steveluscher** [comment]
Moving this discussion over to https://github.com/brave/brave-browser/issues/28955.

(@jordansexton, I can't close this issue myself)

**Comment by jordansexton** [comment]
Closed per @steveluscher, thanks for looking into this everyone!

**Comment by yrliou** [comment]
@yamijuan Thanks for the report, we've merged a fix in Brave Nightly, it should be working now on our latest Nightly, if you could help confirm that it's also fixed on your end, that would be great. We're in the process of uplifting the fix into Brave Beta and Brave Release, for Brave Beta, it could be this or next week, and for Brave Release, current planned release date is 03/22 (next week). Thanks!
